# Generated by Django 4.1.6 on 2023-03-20 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0003_subcategory_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='brand_name',
            new_name='brandname',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_id',
            new_name='categoryid',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory_name',
            new_name='subcategoryname',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='category_id',
            new_name='categoryid',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='fuel_type',
            new_name='fueltype',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='mobile_no',
            new_name='mobileno',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='model_year',
            new_name='modelyear',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='no_of_seats',
            new_name='noofseats',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='owner_name',
            new_name='ownername',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='registration_no',
            new_name='registrationno',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='subcategory_id',
            new_name='subcategoryid',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='transmission_type',
            new_name='transmissiontype',
        ),
    ]
