# Generated by Django 4.1.6 on 2023-03-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0004_rename_brand_name_subcategory_brandname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='fueltype',
            new_name='fuel_type',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='mobileno',
            new_name='mobile_no',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='modelyear',
            new_name='model_year',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='noofseats',
            new_name='no_of_seats',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='ownername',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='registrationno',
            new_name='registration_no',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='transmissiontype',
            new_name='transmission_type',
        ),
    ]
